"""require users auth_user_id

Revision ID: 81906b9ae677
Revises: 384eb7c3a754
Create Date: 2026-10-08 13:45:26.774290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81906b9ae677'
down_revision: Union[str, Sequence[str], None] = '384eb7c3a754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('auth_user_id',
               existing_type=sa.Uuid(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('auth_user_id',
               existing_type=sa.Uuid(),
               nullable=True)

    # ### end Alembic commands ###
