"""drop unused github credential token columns

Revision ID: 384eb7c3a754
Revises: 9f1cac4ccc32
Create Date: 2026-10-08 13:30:59.015714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384eb7c3a754'
down_revision: Union[str, Sequence[str], None] = '9f1cac4ccc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_credentials', schema=None) as batch_op:
        batch_op.drop_column('access_token_expires_at')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('refresh_token_expires_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###
